language: go
go:
  - 1.12.x
  - 1.13.x
  - tip

env:
  - GO111MODULE=on
  - GOFLAGS='-mod vendor

install:
  - go build
  - go install github.com/onsi/ginkgo/ginkgo
  - export PATH=$PATH:$HOME/gopath/bin

script: $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --randomizeSuites --race --trace && go vet

