language: go

go:
  - 1.12.x
  - 1.13.x
  - tip

env:
  global:
    - GO111MODULE=on
    - PATH=${TRAVIS_BUILD_DIR}/bin:${PATH}

before_script:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

git:
  depth: 1

install: true

script:
  - go test -v ./...
  - $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --coverpkg gitserver --trace --race --compilers=2

#
#os:
#  - linux
#  - osx
#  - windows

after_success:
  - gover . coverage.txt
  - ls -al
  - cat coverage.txt
  - bash <(curl -s https://codecov.io/bash)
